package:
    name: ghost
    version: "0.1.0"

source:
    git_url: https://github.com/nelpy/ghost.git

build:
    script: python setup.py install
    number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - matplotlib

  run:
    - python
    - python
    - numpy x.x
    - scipy
    - matplotlib
